version: "3.9"

services:
  spacebar-server:
    container_name: spacebar
    image: ghcr.io/spacebarchat/server:latest
    ports:
      - "3001:3001"
    environment:
      - DATABASE=sqlite://database.db
      - PORT=3001
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./files:/app/files