version: "3.9"

services:
  spacebar-server:
    container_name: spacebar
    image: spacebarchat/server:latest-sqlite
    platform: linux/amd64
    ports:
      - "443:443"   # expose HTTPS
    environment:
      - DATABASE=/exec/persistent/database/database.db
      - STORAGE_PROVIDER=file
      - STORAGE_LOCATION=/exec/persistent/storage/
      - PORT=443
      - TLS_AUTOGEN=true     # <-- tells Spacebar to auto-generate a self-signed cert
      - ENABLE_TLS=true
    volumes:
      - ./data:/exec/persistent/database
      - ./storage:/exec/persistent/storage
      - ./config:/app/config
      - ./certs:/app/config/certs

